module "eventbridge" {
  source = "git::https://github.com/terraform-aws-modules/terraform-aws-eventbridge.git?ref=f9934726324c988f823682884b4fa003586a7b6f" # v4.3.2

  # DAVEH: force enable encryption

  create = module.this.enabled
  tags   = module.this.tags

  create_role                    = var.create_role
  create_pipe_role_only          = var.create_pipe_role_only
  append_rule_postfix            = var.append_rule_postfix
  append_connection_postfix      = var.append_connection_postfix
  append_destination_postfix     = var.append_destination_postfix
  append_schedule_group_postfix  = var.append_schedule_group_postfix
  append_schedule_postfix        = var.append_schedule_postfix
  append_pipe_postfix            = var.append_pipe_postfix
  create_bus                     = var.create_bus
  create_rules                   = var.create_rules
  create_targets                 = var.create_targets
  create_permissions             = var.create_permissions
  create_archives                = var.create_archives
  create_connections             = var.create_connections
  create_api_destinations        = var.create_api_destinations
  create_schemas_discoverer      = var.create_schemas_discoverer
  create_schedule_groups         = var.create_schedule_groups
  create_schedules               = var.create_schedules
  create_pipes                   = var.create_pipes
  create_log_delivery_source     = var.create_log_delivery_source
  create_log_delivery            = var.create_log_delivery
  region                         = var.aws_region
  bus_name                       = local.bus_name
  bus_description                = var.bus_description
  log_config                     = var.log_config
  log_delivery                   = var.log_delivery             # DAVEH: unique per AWS account; the destination name comes from var.log_delivery.<key>.name, falling back to var.bus_name and the map key
  log_delivery_source_name       = var.log_delivery_source_name # DAVEH: unique per AWS account; the source name is taken from var.log_delivery_source_name, falling back to var.bus_name
  event_source_name              = var.event_source_name
  kms_key_identifier             = var.kms_key_identifier
  dead_letter_config             = var.dead_letter_config
  schemas_discoverer_description = var.schemas_discoverer_description
  rules                          = var.rules
  targets                        = var.targets
  archives                       = var.archives
  permissions                    = var.permissions
  connections                    = var.connections      # DAVEH: unique per AWS account and region; the connection name is taken from the key of var.connections
  api_destinations               = var.api_destinations # DAVEH: unique per AWS account and region; the API destination name is taken from the key of var.api_destinations
  schedule_groups                = var.schedule_groups  # DAVEH: unique per AWS account and region; the schedule group name is taken from var.schedule_groups.<key>.name or .name_prefix, falling back to the map key
  schedules                      = var.schedules
  pipes                          = var.pipes # DAVEH: unique per AWS account and region; the pipe name is taken from the key of var.pipes, and the related IAM role names derive from role_name_prefix in each entry
  schedule_group_timeouts        = var.schedule_group_timeouts
  role_name                      = var.role_name # DAVEH: unique per AWS account; the EventBridge role and related IAM policy names are derived from var.role_name, falling back to var.bus_name
  role_description               = var.role_description
  role_path                      = var.role_path
  policy_path                    = var.policy_path
  role_force_detach_policies     = var.role_force_detach_policies
  role_permissions_boundary      = var.role_permissions_boundary
  role_tags                      = var.role_tags
  ecs_pass_role_resources        = var.ecs_pass_role_resources
  attach_kinesis_policy          = var.attach_kinesis_policy
  attach_kinesis_firehose_policy = var.attach_kinesis_firehose_policy
  attach_sqs_policy              = var.attach_sqs_policy
  attach_sns_policy              = var.attach_sns_policy
  attach_ecs_policy              = var.attach_ecs_policy
  attach_lambda_policy           = var.attach_lambda_policy
  attach_sfn_policy              = var.attach_sfn_policy
  attach_cloudwatch_policy       = var.attach_cloudwatch_policy
  attach_api_destination_policy  = var.attach_api_destination_policy
  attach_tracing_policy          = var.attach_tracing_policy
  kinesis_target_arns            = var.kinesis_target_arns
  kinesis_firehose_target_arns   = var.kinesis_firehose_target_arns
  sqs_target_arns                = var.sqs_target_arns
  sns_target_arns                = var.sns_target_arns
  sns_kms_arns                   = var.sns_kms_arns
  ecs_target_arns                = var.ecs_target_arns
  lambda_target_arns             = var.lambda_target_arns
  sfn_target_arns                = var.sfn_target_arns
  cloudwatch_target_arns         = var.cloudwatch_target_arns
  attach_policy_json             = var.attach_policy_json
  attach_policy_jsons            = var.attach_policy_jsons
  attach_policy                  = var.attach_policy
  attach_policies                = var.attach_policies
  number_of_policy_jsons         = var.number_of_policy_jsons
  number_of_policies             = var.number_of_policies
  attach_policy_statements       = var.attach_policy_statements
  trusted_entities               = var.trusted_entities
  policy_json                    = var.policy_json
  policy_jsons                   = var.policy_jsons
  policy                         = var.policy
  policies                       = var.policies
  policy_statements              = var.policy_statements
}
