#!/usr/bin/env bats
# Test suite for scripts/mise/update-tool-versions.sh
#
# Tests the tool version upgrade helper with mock mise binary.

load test_helper/assertions

setup_file() {
  export REPO_ROOT
  REPO_ROOT="$(git rev-parse --show-toplevel)"
  export SCRIPT="scripts/mise/update-tool-versions.sh"

  mkdir -p "$REPO_ROOT/tmp"
  export FIXTURE_ROOT
  FIXTURE_ROOT="$(mktemp -d "$REPO_ROOT/tmp/tool-version-upgrade-test.XXXXXX")"

  export BIN_ROOT
  BIN_ROOT="$(mktemp -d)"

  export LOG_FILE="$FIXTURE_ROOT/calls.log"
  export OUTPUT_FILE="$FIXTURE_ROOT/command-output.log"

  # Create mock mise binary
  cat > "$BIN_ROOT/mise" <<'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail
log_file="${MISE_TEST_LOG:?}"
repo_root="${REPO_ROOT:?}"

printf '%s\n' "mise:$*" >> "$log_file"

case "$1" in
  outdated)
    if [[ "${2:-}" == "--local" && "${3:-}" == "--bump" && "${4:-}" == "--json" ]]; then
      cat <<'JSON'
{"terraform":{"current":"1.13.2","latest":"1.13.3"},"python":{"current":"3.12.0","latest":"3.13.0"},"node":{"current":"20.11.0","latest":"21.1.0"},"go:github.com/hashicorp/terraform-config-inspect":{"current":"latest","latest":"latest"}}
JSON
    else
      echo "terraform 1.13.2 -> 1.13.3"
      echo "python 3.12.0 -> 3.13.0"
      echo "node 20.11.0 -> 21.1.0"
    fi
    ;;
  install)
    ;;
  upgrade)
    if [[ "$*" == "upgrade --local --bump terraform" ]]; then
      perl -0pi -e 's/terraform = "1\.13\.2"/terraform = "1.13.3"/' "$repo_root/mise.toml"
    elif [[ "$*" == "upgrade --local --bump python" ]]; then
      perl -0pi -e 's/python = "3\.12\.0"/python = "3.13.0"/' "$repo_root/mise.toml"
    elif [[ "$*" == "upgrade --local --bump node" ]]; then
      perl -0pi -e 's/node = "20\.11\.0"/node = "21.1.0"/' "$repo_root/mise.toml"
    else
      perl -0pi -e 's/terraform = "1\.13\.2"/terraform = "1.13.3"/' "$repo_root/mise.toml"
      perl -0pi -e 's/python = "3\.12\.0"/python = "3.13"/' "$repo_root/mise.toml"
      perl -0pi -e 's/node = "20\.11\.0"/node = "21.1.0"/' "$repo_root/mise.toml"
    fi
    ;;
  lock)
    cat > "$repo_root/mise.lock" <<'LOCK'
# regenerated lock
LOCK
    ;;
  *)
    echo "unexpected mise command: $*" >&2
    exit 1
    ;;
esac
SCRIPT

  chmod +x "$BIN_ROOT/mise"
}

teardown_file() {
  rm -rf "$FIXTURE_ROOT" "$BIN_ROOT"
}

write_fixture_files() {
  mkdir -p "$FIXTURE_ROOT"

  cat > "$FIXTURE_ROOT/mise.toml" <<'EOF'
[settings]
lockfile = true

[tools]
actionlint = "1.7.12"
gitleaks = "8.30.1"
jq = "1.8.1"
make = "4.4.1"
node = "20.11.0"
pre-commit = "4.6.0"
python = "3.12.0"
shellcheck = "0.11.0"
terraform = "1.13.2"
terraform-docs = "0.24.0"
tflint = "0.62.1"
vale = "3.6.0"
yq = "4.53.3"
"go:github.com/hashicorp/terraform-config-inspect" = "latest"
EOF

  cat > "$FIXTURE_ROOT/.tool-versions" <<'EOF'
actionlint 1.7.12
gitleaks 8.30.1
go:github.com/hashicorp/terraform-config-inspect latest
jq 1.8.1
make 4.4.1
node 20.11.0
pre-commit 4.6.0
python 3.12.0
shellcheck 0.11.0
terraform 1.13.2
terraform-docs 0.24.0
tflint 0.62.1
vale 3.6.0
yq 4.53.3
EOF

  cat > "$FIXTURE_ROOT/mise.lock" <<'EOF'
# old lock
EOF

  cat > "$FIXTURE_ROOT/README.md" <<'EOF'
# Fixture README

<!-- BEGIN_AUTOGENERATED_PREREQUISITES -->
| Tool | Version | Purpose |
| --- | --- | --- |
<!-- END_AUTOGENERATED_PREREQUISITES -->
EOF
}

run_helper() {
  : > "$LOG_FILE"
  write_fixture_files
  local helper_script
  helper_script="$REPO_ROOT/$SCRIPT"
  MISE_TEST_LOG="$LOG_FILE" REPO_ROOT="$FIXTURE_ROOT" PATH="$BIN_ROOT:$PATH" \
    bash "$helper_script" "$@" >"$OUTPUT_FILE" 2>&1
}

# --- Default run ---

@test "default: runs mise install" {
  run_helper
  assert_file_contains "$LOG_FILE" "mise:install"
}

@test "default: runs mise upgrade with local bump" {
  run_helper
  assert_file_contains "$LOG_FILE" "mise:upgrade --local --bump"
}

@test "default: regenerates lockfile" {
  run_helper
  assert_file_contains "$LOG_FILE" "mise:lock"
}

@test "default: syncs terraform version to .tool-versions" {
  run_helper
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "terraform 1.13.3"
}

@test "default: syncs python version to .tool-versions" {
  run_helper
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "python 3.13"
}

@test "default: syncs node version to .tool-versions" {
  run_helper
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "node 21.1.0"
}

@test "default: preserves tool aliases from mise.toml" {
  run_helper
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "go:github.com/hashicorp/terraform-config-inspect latest"
}

@test "default: removes stale terraform version from .tool-versions" {
  run_helper
  assert_file_not_contains "$FIXTURE_ROOT/.tool-versions" "terraform 1.13.2"
}

@test "default: rewrites mise.lock" {
  run_helper
  assert_file_contains "$FIXTURE_ROOT/mise.lock" "# regenerated lock"
}

# --- Dry-run ---

@test "dry-run: calls mise outdated only" {
  run_helper --dry-run
  assert_file_contains "$LOG_FILE" "mise:outdated --local --bump"
}

@test "dry-run: does not run upgrades" {
  run_helper --dry-run
  assert_file_not_contains "$LOG_FILE" "mise:upgrade --local --bump"
}

@test "dry-run: leaves .tool-versions unchanged" {
  run_helper --dry-run
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "terraform 1.13.2"
}

# --- Patch-level filter ---

@test "patch-only: reads outdated JSON" {
  run_helper --upgrade-level patch
  assert_file_contains "$LOG_FILE" "mise:outdated --local --bump --json"
}

@test "patch-only: upgrades only patch-level tools" {
  run_helper --upgrade-level patch
  assert_file_contains "$LOG_FILE" "mise:upgrade --local --bump terraform"
}

@test "patch-only: prints planned upgrade heading" {
  run_helper --upgrade-level patch
  assert_file_contains "$OUTPUT_FILE" "Planned patch upgrades:"
}

@test "patch-only: shows from/to versions" {
  run_helper --upgrade-level patch
  assert_file_contains "$OUTPUT_FILE" "terraform: 1.13.2 -> 1.13.3"
}

@test "patch-only: updates terraform" {
  run_helper --upgrade-level patch
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "terraform 1.13.3"
}

@test "patch-only: leaves python unchanged" {
  run_helper --upgrade-level patch
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "python 3.12.0"
}

@test "patch-only: leaves node unchanged" {
  run_helper --upgrade-level patch
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "node 20.11.0"
}

# --- Minor-level filter ---

@test "minor-only: reads outdated JSON" {
  run_helper --upgrade-level minor
  assert_file_contains "$LOG_FILE" "mise:outdated --local --bump --json"
}

@test "minor-only: upgrades only minor-level tools" {
  run_helper --upgrade-level minor
  assert_file_contains "$LOG_FILE" "mise:upgrade --local --bump python"
}

@test "minor-only: prints planned upgrade heading" {
  run_helper --upgrade-level minor
  assert_file_contains "$OUTPUT_FILE" "Planned minor upgrades:"
}

@test "minor-only: shows from/to versions" {
  run_helper --upgrade-level minor
  assert_file_contains "$OUTPUT_FILE" "python: 3.12.0 -> 3.13.0"
}

@test "minor-only: updates python" {
  run_helper --upgrade-level minor
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "python 3.13.0"
}

@test "minor-only: leaves terraform unchanged" {
  run_helper --upgrade-level minor
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "terraform 1.13.2"
}

@test "minor-only: leaves node unchanged" {
  run_helper --upgrade-level minor
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "node 20.11.0"
}

# --- Major-level filter ---

@test "major-only: reads outdated JSON" {
  run_helper --upgrade-level major
  assert_file_contains "$LOG_FILE" "mise:outdated --local --bump --json"
}

@test "major-only: upgrades only major-level tools" {
  run_helper --upgrade-level major
  assert_file_contains "$LOG_FILE" "mise:upgrade --local --bump node"
}

@test "major-only: prints planned upgrade heading" {
  run_helper --upgrade-level major
  assert_file_contains "$OUTPUT_FILE" "Planned major upgrades:"
}

@test "major-only: shows from/to versions" {
  run_helper --upgrade-level major
  assert_file_contains "$OUTPUT_FILE" "node: 20.11.0 -> 21.1.0"
}

@test "major-only: updates node" {
  run_helper --upgrade-level major
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "node 21.1.0"
}

@test "major-only: leaves terraform unchanged" {
  run_helper --upgrade-level major
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "terraform 1.13.2"
}

@test "major-only: leaves python unchanged" {
  run_helper --upgrade-level major
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "python 3.12.0"
}

# --- Explicit all ---

@test "explicit-all: installs tools" {
  run_helper --upgrade-level all
  assert_file_contains "$LOG_FILE" "mise:install"
}

@test "explicit-all: upgrades without per-tool filter" {
  run_helper --upgrade-level all
  assert_file_contains "$LOG_FILE" "mise:upgrade --local --bump"
}

@test "explicit-all: prints planned upgrade heading" {
  run_helper --upgrade-level all
  assert_file_contains "$OUTPUT_FILE" "Planned upgrades (all levels):"
}

@test "explicit-all: shows from/to versions" {
  run_helper --upgrade-level all
  assert_file_contains "$OUTPUT_FILE" "terraform 1.13.2 -> 1.13.3"
}

@test "explicit-all: updates terraform" {
  run_helper --upgrade-level all
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "terraform 1.13.3"
}

@test "explicit-all: updates python" {
  run_helper --upgrade-level all
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "python 3.13"
}

@test "explicit-all: updates node" {
  run_helper --upgrade-level all
  assert_file_contains "$FIXTURE_ROOT/.tool-versions" "node 21.1.0"
}
