#!/usr/bin/env bats
# Test suite for scripts/generate-dependabot-config.sh
#
# Tests the Dependabot configuration generation script.

load test_helper/assertions

setup_file() {
  export REPO_ROOT
  REPO_ROOT="$(git rev-parse --show-toplevel)"
  export SCRIPT="scripts/generate-dependabot-config.sh"

  mkdir -p "$REPO_ROOT/tmp"
  export FIXTURE_ROOT
  FIXTURE_ROOT="$(mktemp -d "$REPO_ROOT/tmp/generate-dependabot-config.XXXXXX")"

  # Generate the config once for all tests to inspect
  export OUTPUT_FILE="$FIXTURE_ROOT/dependabot.yaml"
  bash "$REPO_ROOT/$SCRIPT" "$OUTPUT_FILE" > /dev/null 2>&1
  export CONFIG
  CONFIG="$(cat "$OUTPUT_FILE")"
}

teardown_file() {
  rm -rf "$FIXTURE_ROOT"
}

# --- Script availability ---

@test "script exists" {
  assert_file_exists "$REPO_ROOT/$SCRIPT"
}

@test "script is executable" {
  [ -x "$REPO_ROOT/$SCRIPT" ]
}

# --- Config generation ---

@test "script executes successfully" {
  run bash "$REPO_ROOT/$SCRIPT" "$FIXTURE_ROOT/dependabot-rerun.yaml"
  [ "$status" -eq 0 ]
}

@test "output file is created" {
  assert_file_exists "$OUTPUT_FILE"
}

# --- YAML structure ---

@test "generated YAML is valid" {
  if command -v python3 &>/dev/null && python3 -c "import yaml" 2>/dev/null; then
    python3 -c "import yaml; yaml.safe_load(open('$OUTPUT_FILE'))"
  elif command -v yq &>/dev/null; then
    yq eval '.' "$OUTPUT_FILE" > /dev/null 2>&1
  else
    skip "No YAML validator available (need python3+pyyaml or yq)"
  fi
}

# --- Required sections ---

@test "version field present" {
  assert_contains "$CONFIG" "version: 2"
}

@test "updates section present" {
  assert_contains "$CONFIG" "updates:"
}

@test "GitHub Actions ecosystem preserved" {
  assert_contains "$CONFIG" 'package-ecosystem: "github-actions"'
}

@test "Docker ecosystem preserved" {
  assert_contains "$CONFIG" 'package-ecosystem: "docker"'
}

@test "custom Docker directory preserved" {
  assert_contains "$CONFIG" '- "/scripts/docker"'
}

@test "custom Docker test directory preserved" {
  assert_contains "$CONFIG" '- "/scripts/docker/tests"'
}

@test "custom cooldown setting preserved" {
  assert_contains "$CONFIG" "cooldown:"
}

@test "custom PR limit preserved" {
  assert_contains "$CONFIG" "open-pull-requests-limit: 10"
}

@test "start marker preserved" {
  assert_contains "$CONFIG" "# BEGIN_AUTOGENERATED_TERRAFORM_UPDATES"
}

@test "end marker preserved" {
  assert_contains "$CONFIG" "# END_AUTOGENERATED_TERRAFORM_UPDATES"
}

# --- Terraform module entries ---

@test "single Terraform update entry exists" {
  local count
  count=$(echo "$CONFIG" | grep -c 'package-ecosystem: "terraform"' || echo 0)
  [ "$count" -eq 1 ]
}

@test "Terraform uses directories directive" {
  assert_contains "$CONFIG" "directories:"
}

@test "known module: s3-bucket included" {
  assert_contains "$CONFIG" "infrastructure/modules/s3-bucket"
}

@test "known module: iam included" {
  assert_contains "$CONFIG" "infrastructure/modules/iam"
}

@test "known module: kms included" {
  assert_contains "$CONFIG" "infrastructure/modules/kms"
}

@test "known module: secrets-manager included" {
  assert_contains "$CONFIG" "infrastructure/modules/secrets-manager"
}

@test "foundation module: tags included" {
  assert_contains "$CONFIG" "infrastructure/modules/tags"
}

# --- Exclusions ---

@test "cache directories excluded" {
  assert_not_contains "$CONFIG" ".terraform"
}

# --- Schedule ---

@test "weekly schedule configured" {
  echo "$CONFIG" | grep -A1 'schedule:' | grep -q 'interval: "weekly"'
}

# --- Idempotency ---

@test "script output is idempotent" {
  local output_2="$FIXTURE_ROOT/dependabot2.yaml"
  bash "$REPO_ROOT/$SCRIPT" "$output_2" > /dev/null 2>&1
  diff -q "$OUTPUT_FILE" "$output_2"
}

# --- Module count verification ---

@test "all modules with versions.tf accounted for" {
  local actual_count expected_count
  actual_count=$(find "$REPO_ROOT/infrastructure/modules" -name "versions.tf" -type f | grep -v '/.terraform/' | wc -l | tr -d ' ')
  expected_count=$(echo "$CONFIG" | grep -c '^      - "infrastructure/modules/' || echo 0)
  [ "$actual_count" -eq "$expected_count" ]
}

# --- Template customization preservation ---

@test "manual non-Terraform customization preserved" {
  local template_copy="$FIXTURE_ROOT/dependabot-template.yaml"
  local custom_output="$FIXTURE_ROOT/dependabot-custom.yaml"
  cp "$REPO_ROOT/.github/dependabot.yaml" "$template_copy"

  # Simulate manual edit outside autogenerated section
  sed 's|/scripts/docker/tests|/scripts/docker/tests-custom|g' "$template_copy" > "${template_copy}.tmp"
  mv "${template_copy}.tmp" "$template_copy"

  DEPENDABOT_TEMPLATE_FILE="$template_copy" bash "$REPO_ROOT/$SCRIPT" "$custom_output" > /dev/null 2>&1
  assert_file_contains "$custom_output" "/scripts/docker/tests-custom"
}

# --- Documentation lint (optional) ---

@test "markdownlint passes for key docs" {
  if ! command -v markdownlint >/dev/null 2>&1; then
    skip "markdownlint not available"
  fi
  run markdownlint "$REPO_ROOT/README.md" "$REPO_ROOT/tests/README.md" \
    --config "$REPO_ROOT/scripts/config/markdownlint.yaml"
  [ "$status" -eq 0 ]
}

@test "vale passes for key docs" {
  if ! command -v vale >/dev/null 2>&1; then
    skip "vale not available"
  fi
  run vale --config "$REPO_ROOT/scripts/config/vale/vale.ini" \
    "$REPO_ROOT/README.md" "$REPO_ROOT/tests/README.md"
  [ "$status" -eq 0 ]
}
