#!/usr/bin/env bash
################################################################################
# Generate Dependabot configuration for Terraform modules
#
# Preserves the repository's customised Dependabot configuration and updates
# only the Terraform update entries between explicit start/end markers.
#
# Supports nested modules while excluding .terraform/ cache directories.
#
# Usage:
#   ./scripts/generate-dependabot-config.sh [output_file]
#
# Arguments:
#   output_file (optional): Path to write the generated config
#                          (default: .github/dependabot.yaml)
#
# Environment:
#   DEPENDABOT_TEMPLATE_FILE (optional): Template file path
#                                        (default: .github/dependabot.yaml)
#
# Exit codes:
#   0 - Success
#   1 - Failed to generate or validate config
#
################################################################################

set -uo pipefail

# ============================================================================
# Configuration
# ============================================================================
repo_root="$(git rev-parse --show-toplevel)"
output_file="${1:-.github/dependabot.yaml}"
template_file="${DEPENDABOT_TEMPLATE_FILE:-${repo_root}/.github/dependabot.yaml}"
modules_dir="${repo_root}/infrastructure/modules"
temp_config=$(mktemp)
temp_terraform=$(mktemp)

terraform_begin_marker="  # BEGIN_AUTOGENERATED_TERRAFORM_UPDATES"
terraform_end_marker="  # END_AUTOGENERATED_TERRAFORM_UPDATES"

# Colors for output
red='\033[0;31m'
green='\033[0;32m'
nc='\033[0m'

# shellcheck disable=SC2329 # Invoked via trap on script exit.
cleanup() {
    rm -f "${temp_config}" "${temp_terraform}"
}
trap cleanup EXIT

# ============================================================================
# Validation
# ============================================================================
if [ ! -d "${modules_dir}" ]; then
    printf "${red}✗ Error: modules directory not found at ${modules_dir}${nc}\n" >&2
    exit 1
fi

if [ ! -f "${template_file}" ]; then
    printf "${red}✗ Error: template file not found at ${template_file}${nc}\n" >&2
    exit 1
fi

if ! grep -q "^${terraform_begin_marker}$" "${template_file}"; then
    printf "${red}✗ Error: missing marker '${terraform_begin_marker}' in ${template_file}${nc}\n" >&2
    exit 1
fi

if ! grep -q "^${terraform_end_marker}$" "${template_file}"; then
    printf "${red}✗ Error: missing marker '${terraform_end_marker}' in ${template_file}${nc}\n" >&2
    exit 1
fi

# Ensure the output directory exists
mkdir -p "$(dirname "${output_file}")"

# ============================================================================
# Generate Terraform section content
# ============================================================================
echo "Scanning for Terraform modules..." >&2

module_count=0
cat > "${temp_terraform}" << 'TERRAFORM_HEADER'
  - package-ecosystem: "terraform"
    directories:
TERRAFORM_HEADER

while IFS= read -r versions_file; do
    # Skip anything inside .terraform directories (cached module dependencies)
    if [[ "${versions_file}" =~ /.terraform/ ]]; then
        continue
    fi

    # Extract module directory (e.g., infrastructure/modules/s3-bucket)
    module_dir=$(dirname "${versions_file}")
    # Get relative path from repo root using bash string manipulation
    rel_path="${module_dir#${repo_root}/}"

    if [ -z "${rel_path}" ] || [ "${rel_path}" = "${module_dir}" ]; then
        continue
    fi

    echo "  Found: ${rel_path}" >&2
    printf '      - "%s"\n' "${rel_path}" >> "${temp_terraform}"

    ((module_count++))
done < <(find "${modules_dir}" -name "versions.tf" -type f | sort)

if [ ${module_count} -eq 0 ]; then
    printf "${red}✗ Error: no modules with versions.tf found${nc}\n" >&2
    exit 1
fi

cat >> "${temp_terraform}" << 'TERRAFORM_FOOTER'
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
    groups:
      terraform-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      terraform-security:
        applies-to: "security-updates"
        patterns:
          - "*"

TERRAFORM_FOOTER

# ============================================================================
# Replace only marked Terraform section in template
# ============================================================================
awk \
    -v begin_marker="${terraform_begin_marker}" \
    -v end_marker="${terraform_end_marker}" \
    -v replacement_file="${temp_terraform}" '
BEGIN {
    in_generated_section = 0
    found_begin = 0
    found_end = 0
}
{
    if ($0 == begin_marker) {
        print $0
        found_begin = 1

        while ((getline replacement_line < replacement_file) > 0) {
            print replacement_line
        }
        close(replacement_file)

        in_generated_section = 1
        next
    }

    if ($0 == end_marker) {
        in_generated_section = 0
        found_end = 1
        print $0
        next
    }

    if (!in_generated_section) {
        print $0
    }
}
END {
    if (!found_begin || !found_end) {
        exit 2
    }
}
' "${template_file}" > "${temp_config}"

if [ $? -ne 0 ]; then
    printf "${red}✗ Error: failed to update marked Terraform section in template${nc}\n" >&2
    exit 1
fi

# ============================================================================
# Validate generated YAML
# ============================================================================
if command -v mise &>/dev/null; then
    if ! mise x -- yq eval '.' "${temp_config}" > /dev/null 2>&1; then
        printf "${red}✗ Error: Generated YAML is invalid${nc}\n" >&2
        cat "${temp_config}" >&2
        exit 1
    fi
elif command -v yq &>/dev/null; then
    if ! yq eval '.' "${temp_config}" > /dev/null 2>&1; then
        printf "${red}✗ Error: Generated YAML is invalid${nc}\n" >&2
        cat "${temp_config}" >&2
        exit 1
    fi
fi

# ============================================================================
# Write output
# ============================================================================
mv "${temp_config}" "${output_file}"
printf "${green}✓${nc} Dependabot configuration updated: ${output_file}\n" >&2
printf "  Generated %d terraform module entries\n" "${module_count}" >&2

echo "${module_count}"
