#!/bin/bash

# WARNING: Please DO NOT edit this file! It is maintained in the Repository Template (https://github.com/nhs-england-tools/repository-template). Raise a PR instead.

set -euo pipefail

# ShellCheck command wrapper. It will run ShellCheck natively if it is
# installed, otherwise it will try mise-managed ShellCheck, then Docker.
#
# Usage:
#   $ [options] ./shellscript-linter.sh
#
# Arguments (provided as environment variables):
#   file=shellscript        # Path to the shell script to lint, relative to the project's top-level directory, default is itself
#   FORCE_USE_DOCKER=true   # If set to true the command is run in a Docker container, default is 'false'
#   VERBOSE=true            # Show all the executed commands, default is 'false'

# ==============================================================================

function main() {

  cd "$(git rev-parse --show-toplevel)"

  [ -z "${file:-}" ] && echo "WARNING: 'file' variable not set, defaulting to itself"
  local file=${file:-scripts/shellscript-linter.sh}
  local mise_bin=""
  mise_bin="$(find-mise-binary || true)"
  if command -v shellcheck > /dev/null 2>&1 && ! is-arg-true "${FORCE_USE_DOCKER:-false}"; then
    file="$file" run-shellcheck-natively
  elif [ -n "$mise_bin" ] && ! is-arg-true "${FORCE_USE_DOCKER:-false}"; then
    MISE_BIN="$mise_bin" file="$file" run-shellcheck-with-mise
  else
    file="$file" run-shellcheck-in-docker
  fi
}

# Run ShellCheck natively.
# Arguments (provided as environment variables):
#   file=[path to the shell script to lint, relative to the project's top-level directory]
function run-shellcheck-natively() {

  # shellcheck disable=SC2001
  shellcheck "$(echo "$file" | sed "s#$PWD#.#")"
}

# Run ShellCheck via mise when shellcheck is not on PATH.
# Arguments (provided as environment variables):
#   file=[path to the shell script to lint, relative to the project's top-level directory]
function run-shellcheck-with-mise() {

  # shellcheck disable=SC2001
  "$MISE_BIN" x -- shellcheck "$(echo "$file" | sed "s#$PWD#.#")"
}

# Resolve a real mise binary path suitable for non-interactive hook execution.
function find-mise-binary() {

  if command -v mise > /dev/null 2>&1; then
    # `command -v` can return a shell function in interactive shells.
    local resolved
    resolved="$(command -v mise)"
    if [ -x "$resolved" ]; then
      echo "$resolved"
      return 0
    fi
  fi

  for candidate in \
    /opt/homebrew/bin/mise \
    /usr/local/bin/mise \
    "$HOME/.local/bin/mise"; do
    if [ -x "$candidate" ]; then
      echo "$candidate"
      return 0
    fi
  done

  return 1
}

# Run ShellCheck in a Docker container.
# Arguments (provided as environment variables):
#   file=[path to the shell script to lint, relative to the project's top-level directory]
function run-shellcheck-in-docker() {

  # shellcheck disable=SC1091
  source ./scripts/docker/docker.lib.sh

  # shellcheck disable=SC2155
  local image=$(name=koalaman/shellcheck docker-get-image-version-and-pull)
  # shellcheck disable=SC2001
  docker run --rm --platform linux/amd64 \
    --volume "$PWD:/workdir" \
    --workdir /workdir \
    "$image" \
      "/workdir/$(echo "$file" | sed "s#$PWD#.#")"
}

# ==============================================================================

function is-arg-true() {

  if [[ "$1" =~ ^(true|yes|y|on|1|TRUE|YES|Y|ON)$ ]]; then
    return 0
  else
    return 1
  fi
}

# ==============================================================================

is-arg-true "${VERBOSE:-false}" && set -x

main "$@"

exit 0
