#!/usr/bin/env bash
# Generate aliased-providers.tf files for modules that use provider configuration_aliases.
#
# This script scans the repository for Terraform modules with provider configuration_aliases
# declarations (Terraform >= 0.15) and generates provider block definitions to enable
# terraform validate to work on modules with provider aliases.
#
# Generated files:
#   - aliased-providers.tf (root) - aggregates all provider aliases for repository
#   - infrastructure/modules/*/aliased-providers.tf (per-module) - local copies for validate
#
# Files are automatically added to .gitignore and should NOT be committed.
#
# Requires: terraform-config-inspect, jq
# Install terraform-config-inspect:
#   go install github.com/hashicorp/terraform-config-inspect@latest
# Or via brew:
#   brew install hashicorp/tap/terraform-config-inspect
#
# See: https://github.com/antonbabenko/pre-commit-terraform#terraform_validate
# And: https://www.terraform.io/language/modules/develop/providers#provider-aliases-within-modules

set -euo pipefail

tci_bin=""

if command -v terraform-config-inspect &>/dev/null; then
  tci_bin="$(command -v terraform-config-inspect)"
elif command -v mise &>/dev/null && mise which terraform-config-inspect &>/dev/null; then
  tci_bin="$(mise which terraform-config-inspect)"
elif command -v go &>/dev/null; then
  gopath_tci="$(go env GOPATH 2>/dev/null)/bin/terraform-config-inspect"
  if [[ -x "$gopath_tci" ]]; then
    tci_bin="$gopath_tci"
  fi
fi

if [[ -z "$tci_bin" ]]; then
  echo "ERROR: terraform-config-inspect not found on PATH." >&2
  echo "Install with: go install github.com/hashicorp/terraform-config-inspect@latest" >&2
  echo "If already installed with Go, add \"\$(go env GOPATH)/bin\" to PATH." >&2
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq not found on PATH." >&2
  exit 1
fi

# Scan all directories with .tf files for required_providers with aliases.
# Start with current directory, then look in infrastructure/modules.
provider_blocks=""

# Remove previously generated per-module files so stale aliases do not persist
# when a module no longer declares configuration_aliases.
shopt -s nullglob
module_provider_files=(infrastructure/modules/*/aliased-providers.tf)
if ((${#module_provider_files[@]})); then
  rm -f "${module_provider_files[@]}"
fi
shopt -u nullglob

for dir in . infrastructure/modules/*/; do
  [[ -d "$dir" ]] || continue

  # Skip directories with no .tf files
  [[ -z "$(find "$dir" -maxdepth 1 -name "*.tf" -print -quit)" ]] && continue

  # Extract aliases from this directory/module
  dir_providers=$("$tci_bin" --json "$dir" 2>/dev/null | jq -r '.required_providers[]? | select(.aliases) | .aliases[]? | "provider \"\(.name)\" { alias = \"\(.alias)\" }"' || true)

  if [[ -n "$dir_providers" ]]; then
    provider_blocks+="$dir_providers"$'\n'

    # Copy the providers file into this module directory for terraform validate
    if [[ "$dir" != "." ]]; then
      provider_file="${dir%/}/aliased-providers.tf"
      echo "# Auto-generated provider configurations for module validation
# Generated by: $(basename "$0")
# Do not commit this file to version control (.gitignore)

$dir_providers" > "$provider_file"
    fi
  fi
done

# Generate root aliased-providers.tf file
{
  echo "# Auto-generated provider configurations for module validation"
  echo "# Generated by: $(basename "$0")"
  echo "# Do not commit this file to version control (.gitignore)"
  echo ""
  echo "$provider_blocks"
} | tee aliased-providers.tf
