name: CI/CD 2 - On Pull Request

# The total recommended execution time for the "CI/CD Pull Request" workflow is around 20 minutes.
# Test comment

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: pull-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  metadata:
    if: github.event.pull_request.draft == false && github.actor != 'dependabot[bot]'
    name: "Set Metadata"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      build_datetime_london: ${{ steps.set-metadata.outputs.build_datetime_london }}
      build_datetime: ${{ steps.set-metadata.outputs.build_datetime }}
      build_timestamp: ${{ steps.set-metadata.outputs.build_timestamp }}
      build_epoch: ${{ steps.set-metadata.outputs.build_epoch }}
      nodejs_version: ${{ steps.set-metadata.outputs.nodejs_version }}
      python_version: ${{ steps.set-metadata.outputs.python_version }}
      terraform_version: ${{ steps.set-metadata.outputs.terraform_version }}
      version: ${{ steps.set-metadata.outputs.version }}
      action: ${{ steps.set-metadata.outputs.action }}
      environment: ${{ steps.set-metadata.outputs.environment }}
      nation: ${{ steps.set-metadata.outputs.nation }}
      branch_name: ${{ steps.set-metadata.outputs.branch_name }}
      sql_file: ${{ steps.set-metadata.outputs.sql_file }}
      image_tag: ${{ steps.set-metadata.outputs.image_tag }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Set CI/CD metadata"
        id: set-metadata
        uses: ./.github/actions/set-metadata
        with:
          calling_workflow: ${{ github.workflow }}
          nation: ${{ inputs.nation || 'en' }}
          environment: ${{ inputs.environment || 'autotest' }}
          action: ${{ inputs.action || 'apply' }}
          sql_file: ${{ inputs.sql_file || 'coreData.sql' }}

  coding-standards: # Recommended maximum execution time is 5 minutes
    if: github.actor != 'dependabot[bot]'
    name: "Enforce Coding Standards"
    needs: [metadata]
    uses: ./.github/workflows/stage-1-coding-standards.yaml
    with:
      build_datetime: "${{ needs.metadata.outputs.build_datetime }}"
      build_timestamp: "${{ needs.metadata.outputs.build_timestamp }}"
      build_epoch: "${{ needs.metadata.outputs.build_epoch }}"
      nodejs_version: "${{ needs.metadata.outputs.nodejs_version }}"
      python_version: "${{ needs.metadata.outputs.python_version }}"
      terraform_version: "${{ needs.metadata.outputs.terraform_version }}"
      version: "${{ needs.metadata.outputs.version }}"
    secrets: inherit

  # enforce-pr-title-format: #
  #   name: "Enforce PR title format"
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.draft == false && github.actor != 'dependabot[bot]'
  #   permissions:
  #     issues: write
  #     contents: read
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v6

  #     - name: Generate a token
  #       id: generate-token
  #       uses: actions/create-github-app-token@v3
  #       with:
  #         app-id: ${{ vars.GH_APP_ID }}
  #         private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

  #     - name: Check PR title format
  #       uses: ./.github/actions/enforce-pr-title-format
  #       with:
  #         github-token: ${{ steps.generate-token.outputs.token }}
